
server:
  port: 19001
spring:
  datasource:
    one:
      username: root
      password: 65260018@Iot
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://117.78.41.92:3311/eovademo_sy?characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    two:
      username: root
      password: 65260018@Iot
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://117.78.41.92:3311/eova_sy?characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
  jpa:
    show-sql: true
  servlet:
    multipart:
      location: D:/eova_ispts/img-server/pic/temp