
server:
  port: 9002
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.200:3311/eova_test3.27?characterEncoding=UTF-8&serverTimezone=UTC&useUnicode=true
  jpa:
    show-sql: true